
services:
  backend:
    volumes:
      - koneksi_db:/app/koneksi.db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/works"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    volumes:
      - koneksi_db:/app/koneksi.db
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4174:4173"
    environment:
      - VITE_API_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped





volumes:
  koneksi_db:
